// Cadenas de la interfaz. Solo español por ahora; separadas para poder traducir después.
export const t = {
  appName: "Kairos",
  nav: { tenants: "Negocios", brand: "Marca", rewards: "Premios", caja: "Caja", stores: "Sucursales", staff: "Personal" },
  role: { super_admin: "Super Admin", tenant_admin: "Administrador", tenant_staff: "Caja" },
  common: {
    save: "Guardar cambios",
    cancel: "Cancelar",
    create: "Crear negocio",
    edit: "Editar",
    loading: "Cargando…",
    retry: "Reintentar",
    back: "Volver",
    theme: { label: "Modo oscuro", toLight: "Cambiar a tema claro", toDark: "Cambiar a tema oscuro" },
    logout: "Cerrar sesión",
    password: { show: "Mostrar contraseña", hide: "Ocultar contraseña" },
    sidebar: { collapse: "Contraer menú", expand: "Expandir menú", menu: "Menú" },
  },
  login: {
    headline: "Fidelización que se",
    headlineWord: "juega",
    tagline: "Panel de administración de la plataforma Kairos.",
    title: "Iniciar sesión",
    subtitle: "Acceso exclusivo para el administrador de la plataforma.",
    email: "Correo",
    password: "Contraseña",
    submit: "Entrar",
    tabTenant: "Mi negocio",
    tabSuper: "Administrador Kairos",
    slug: "Identificador del negocio",
    slugHint: "El que te dio Kairos, por ejemplo cafeteria-aurora",
    tenantSubtitle: "Ingresa con la cuenta de tu negocio.",
    submitting: "Entrando…",
    error: "Correo o contraseña incorrectos",
    footer: "Kairos · Panel de administración",
  },
  tenants: {
    title: "Panel de",
    titleWord: "negocios",
    new: "Nuevo negocio",
    search: "Buscar por nombre o identificador",
    allStatus: "Todos los estados",
    stats: { total: "Total", active: "Activos", suspended: "Suspendidos" },
    cols: { name: "Negocio", plan: "Plan", status: "Estado", ends: "Vence", actions: "Acciones" },
    empty: "Aún no hay negocios. Crea el primero para empezar.",
    emptyFiltered: "Ningún negocio coincide con la búsqueda.",
    noEnd: "Sin fecha",
    status: { ACTIVE: "Activo", SUSPENDED: "Suspendido", CANCELLED: "Cancelado" },
    plan: { TRIAL: "Prueba", BASIC: "Básico", PRO: "Pro" },
    suspend: "Suspender",
    activate: "Reactivar",
    suspendTitle: "¿Suspender este negocio?",
    suspendBody: (n: string) =>
      `${n} y su personal perderán el acceso de inmediato y se cerrarán sus sesiones. Sus datos se conservan y puedes reactivarlo cuando quieras.`,
    activateTitle: "¿Reactivar este negocio?",
    activateBody: (n: string) => `${n} podrá volver a iniciar sesión.`,
    suspended: (n: string) => `${n} fue suspendido`,
    activated: (n: string) => `${n} fue reactivado`,
    prev: "Anterior",
    next: "Siguiente",
    page: (p: number, total: number) => `Página ${p} de ${total}`,
  },
  form: {
    titleNew: "Nuevo",
    titleNewWord: "negocio",
    titleEdit: "Editar",
    sections: {
      business: "Datos del negocio",
      subscription: "Suscripción",
      brand: "Marca",
      points: "Economía de puntos",
      admin: "Administrador del negocio",
    },
    name: "Nombre comercial",
    slug: "Identificador (URL)",
    slugHint: "Minúsculas, números y guiones. No se puede cambiar después.",
    plan: "Plan",
    ends: "Vence el",
    primary: "Color principal",
    secondary: "Color secundario (opcional)",
    themeMode: "Tema de la Wallet",
    themeModes: { AUTO: "Automático", LIGHT: "Claro", DARK: "Oscuro" },
    scorePerPoint: "Puntos de juego por 1 punto",
    maxPointsPerGame: "Máximo de puntos por partida",
    maxGamesPerDay: "Máximo de partidas por día",
    createAdmin: "Crear el administrador ahora",
    adminHint: "Podrá iniciar sesión en el panel del negocio.",
    adminName: "Nombre",
    adminEmail: "Correo",
    adminPassword: "Contraseña (mínimo 10 caracteres)",
    created: (n: string) => `${n} fue creado`,
    saved: "Cambios guardados",
  },
  preview: {
    title: "Vista previa de la Wallet",
    balance: "Tu saldo",
    pts: "pts",
    redeem: "Canjear",
    reward: "Café gratis",
    cost: "500 pts",
    missing: "Te faltan 120 pts",
    contrastText: "Contraste del texto",
    contrastBg: "Contraste sobre el fondo",
    light: "Claro",
    dark: "Oscuro",
    adjusted: "Ajustado automáticamente",
  },
  errors: {
    generic: "Algo salió mal. Intenta de nuevo.",
    network: "No se pudo conectar con el servidor.",
    required: "Campo obligatorio",
  },
  brand: {
    title: "Marca de tu",
    titleWord: "negocio",
    intro: "Así se verá tu negocio en la Wallet y en la máquina Arcade.",
    logo: "Logo",
    logoHint: "PNG, JPG o WebP. Máximo 1 MB. Mejor con fondo transparente.",
    upload: "Subir logo",
    replace: "Cambiar logo",
    remove: "Quitar logo",
    saved: "Marca actualizada",
  },
  upload: {
    badType: "Usa una imagen PNG, JPG o WebP",
    tooBig: "La imagen supera 1 MB",
    failed: "No se pudo subir la imagen",
    uploading: "Subiendo…",
  },
  rewards: {
    title: "Catálogo de",
    titleWord: "premios",
    intro: "Lo que tus clientes pueden canjear con sus puntos.",
    new: "Nuevo premio",
    empty: "Aún no tienes premios. Crea el primero para que tus clientes tengan algo que ganar.",
    cost: "Costo en puntos",
    stock: "Existencias",
    stockHint: "Déjalo vacío si no tiene límite.",
    unlimited: "Sin límite",
    left: (n: number) => `${n} disponibles`,
    soldOut: "Agotado",
    inactive: "Oculto",
    active: "Visible para clientes",
    name: "Nombre del premio",
    description: "Descripción (opcional)",
    image: "Imagen (opcional)",
    editTitle: "Editar premio",
    newTitle: "Nuevo premio",
    deleteTitle: "¿Eliminar este premio?",
    deleteBody: (n: string) => `${n} dejará de aparecer para tus clientes. Los cupones que ya se emitieron siguen siendo válidos.`,
    delete: "Eliminar",
    saved: "Premio guardado",
    deleted: "Premio eliminado",
    pts: "pts",
    readOnly: "Solo el administrador puede editar el catálogo.",
  },
  caja: {
    title: "Validar",
    titleWord: "cupón",
    intro: "Pide al cliente el código que muestra su teléfono.",
    code: "Código del cupón",
    lookup: "Buscar",
    redeem: "Marcar como entregado",
    another: "Validar otro cupón",
    notFound: "No encontramos ese código. Revisa que esté bien escrito.",
    delivered: "Entregado. Cupón canjeado",
    expiresIn: (m: number) => (m <= 1 ? "Vence en menos de 1 minuto" : `Vence en ${m} min`),
    status: { PENDING: "Listo para entregar", REDEEMED: "Ya canjeado", EXPIRED: "Vencido", CANCELLED: "Cancelado" },
    statusHelp: {
      PENDING: "Entrega el premio y confirma.",
      REDEEMED: "Este cupón ya se usó. No entregues el premio otra vez.",
      EXPIRED: "El cliente debe generar un cupón nuevo.",
      CANCELLED: "Este cupón fue cancelado. No entregues el premio.",
    },
    recent: "Entregas recientes",
    noRecent: "Todavía no hay entregas.",
    by: (n: string) => `por ${n}`,
  },
  stores: {
    title: "Sucursales y",
    titleWord: "máquinas",
    intro: "Cada máquina Arcade se registra con su propia llave pública.",
    new: "Nueva sucursal",
    newTitle: "Nueva sucursal",
    editTitle: "Editar sucursal",
    name: "Nombre",
    address: "Dirección (opcional)",
    active: "Sucursal activa",
    inactive: "Inactiva",
    empty: "Aún no tienes sucursales. Crea la primera para registrar una máquina.",
    storeId: "ID de la sucursal",
    copy: "Copiar",
    copied: "Copiado",
    machines: "Máquinas",
    noMachines: "Sin máquinas registradas.",
    addMachine: "Registrar máquina",
    machineTitle: "Registrar máquina",
    machineLabel: "Nombre de la máquina",
    algorithm: "Algoritmo",
    publicKey: "Llave pública (PEM)",
    publicKeyHint: "Genera el par en tu equipo con: pnpm --filter @kairos/api gen:machine-key nombre. Pega aquí solo la pública. La privada nunca sale de la máquina.",
    machineActive: "Activa",
    machineRevoked: "Revocada",
    revoke: "Revocar",
    revokeTitle: "¿Revocar esta máquina?",
    revokeBody: (n: string) => `${n} dejará de acreditar puntos. Esto no se puede deshacer: para volver a usarla se registra una llave nueva.`,
    saved: "Sucursal guardada",
    machineSaved: "Máquina registrada",
    revoked: "Máquina revocada",
  },
  staff: {
    title: "Personal de",
    titleWord: "caja",
    intro: "Las personas que validan cupones en el mostrador.",
    new: "Nuevo empleado",
    newTitle: "Nuevo empleado",
    editTitle: "Editar empleado",
    name: "Nombre",
    email: "Correo",
    password: "Contraseña (mínimo 10 caracteres)",
    newPassword: "Nueva contraseña (opcional)",
    passwordHint: "Si la cambias, se cierran sus sesiones abiertas.",
    store: "Sucursal",
    allStores: "Todas las sucursales",
    cols: { name: "Empleado", store: "Sucursal", status: "Estado" },
    active: "Activo",
    inactive: "Desactivado",
    activate: "Activar",
    deactivate: "Desactivar",
    deactivateTitle: "¿Desactivar a este empleado?",
    deactivateBody: (n: string) => `${n} perderá el acceso de inmediato y se cerrarán sus sesiones.`,
    empty: "Aún no tienes personal de caja.",
    saved: "Empleado guardado",
    deactivated: "Empleado desactivado",
    activated: "Empleado activado",
    admin: "Administrador",
  },
};
