// Cadenas de la interfaz. Solo español por ahora; separadas para poder traducir después.
export const t = {
  appName: "Kairos",
  nav: { tenants: "Negocios", brand: "Marca", rewards: "Premios", caja: "Caja", stores: "Sucursales", staff: "Personal", plan: "Plan" },
  role: { super_admin: "Super Admin", tenant_admin: "Administrador", tenant_staff: "Caja" },
  common: {
    admin: "Admin",
    navigation: "Navegación principal",
    save: "Guardar cambios",
    cancel: "Cancelar",
    close: "Cerrar",
    create: "Crear negocio",
    edit: "Editar",
    loading: "Cargando…",
    retry: "Reintentar",
    back: "Volver",
    theme: { label: "Modo oscuro", toLight: "Cambiar a tema claro", toDark: "Cambiar a tema oscuro" },
    logout: "Cerrar sesión",
    password: { show: "Mostrar contraseña", hide: "Ocultar contraseña" },
    sidebar: { collapse: "Contraer menú", expand: "Expandir menú", menu: "Menú" },
  },
  login: {
    headline: "Fidelización que se",
    headlineWord: "juega",
    tagline: "Kairos es un programa de lealtad para negocios con local físico. Tus clientes juegan en una máquina Arcade, ganan premios en su celular y vuelven por más. Tú lo controlas desde este panel.",
    title: "Iniciar sesión",
    subtitle: "Acceso exclusivo para el administrador de la plataforma.",
    email: "Correo",
    password: "Contraseña",
    submit: "Entrar",
    tabTenant: "Mi negocio",
    tabSuper: "Administrador Kairos",
    slug: "Identificador del negocio",
    slugHint: "El que te dio Kairos, por ejemplo cafeteria-aurora",
    tenantSubtitle: "Ingresa con la cuenta de tu negocio.",
    submitting: "Entrando…",
    error: "Correo o contraseña incorrectos",
    invalidEmail: "Ingresa un correo válido.",
    required: "Completa este campo.",
    networkError: "No pudimos conectarnos. Revisa tu conexión e intenta de nuevo.",
    rateLimited: "Demasiados intentos. Espera unos minutos antes de volver a entrar.",
    unavailable: "No se pudo iniciar sesión. Intenta de nuevo.",
    footer: "Kairos · Panel de administración",
    trialNote: "Sin tarjeta. Configura tu negocio en minutos.",
    trialPrompt: "¿Aún no tienes cuenta?",
    trialAction: "Prueba gratis",
    backToLogin: "Ya tengo cuenta",
    registerTitle: "Prueba Kairos gratis",
    registerSubtitle: "Crea tu negocio y entra al panel en un minuto. No pedimos tarjeta.",
    businessName: "Nombre de tu negocio",
    adminName: "Tu nombre",
    registerPassword: "Contraseña (mínimo 10 caracteres)",
    registerSubmit: "Crear mi cuenta de prueba",
    registering: "Creando tu cuenta…",
    passwordShort: "Usa al menos 10 caracteres.",
    emailTaken: "No se pudo crear la cuenta. Revisa los datos e intenta de nuevo.",
    registerRateLimited: "Se crearon muchas cuentas desde esta conexión. Intenta más tarde.",
    registered: (slug: string) => `Tu cuenta de prueba está lista. Tu identificador para entrar es ${slug}: guárdalo.`,
  },
  trial: {
    banner: (days: number) => (days === 1 ? "Prueba gratis: te queda 1 día." : `Prueba gratis: te quedan ${days} días.`),
    link: "Ver planes",
  },
  plan: {
    title: "Elige tu",
    titleWord: "plan",
    trialLeft: (days: number) => (days === 1 ? "Tu prueba gratis termina mañana." : `Te quedan ${days} días de prueba gratis.`),
    expiredTitle: "Tu prueba terminó",
    expiredBody: "Elige un plan para volver a usar tu panel, tu caja y tus máquinas. Tus datos se conservan.",
    current: "Tu plan actual",
    request: "Quiero este plan",
    requested: "Plan solicitado",
    requestedNote: "Recibimos tu solicitud. Te avisaremos cuando tu plan esté activo.",
    sent: "Solicitud enviada",
    error: "No se pudo enviar la solicitud. Intenta de nuevo.",
    staffNote: "Solo el administrador de tu negocio puede elegir el plan. Avísale para que lo haga.",
    payNote: "Pago desde el panel: próximamente. Por ahora activamos tu plan a mano después de tu solicitud.",
    perMonth: "/mes",
    free: "Gratis",
    freeFor: (days: number) => `por ${days} días`,
    price: (n: number) => `$${n}`,
    limitStores: (n: number) => (n === 1 ? "1 sucursal" : `Hasta ${n} sucursales`),
    limitMachines: (n: number) => (n === 1 ? "1 máquina Arcade" : `Hasta ${n} máquinas Arcade`),
    inUse: (n: number) => `en uso: ${n}`,
    pricesNote: "Precios en pesos mexicanos (MXN), por mes.",
    limitReached: "Llegaste al límite de tu plan. Sube de plan para agregar más.",
    activeUntil: (plan: string, date: string) => `Plan ${plan} activo hasta el ${date}.`,
    activeNoEnd: (plan: string) => `Plan ${plan} activo, sin fecha de vencimiento.`,
    goPanel: "Ir a mi panel",
    plans: {
      TRIAL: "Prueba gratis",
      BASIC: "Básico",
      PRO: "Pro",
    },
  },
  landing: {
    scroll: "Conoce cómo funciona",
    howTitle: "Así funciona Kairos",
    howIntro: "En lugar de tarjetas de sellos, tus clientes juegan para ganar recompensas en tu negocio. Tú solo defines los premios.",
    how: [
      {
        title: "1. Juegan",
        body: "En tu local, tu cliente juega una partida corta en la máquina Arcade y, al llegar a la meta, gira una ruleta con tus premios.",
      },
      {
        title: "2. Ganan",
        body: "Escanea el código QR con su celular y el premio queda guardado en su Wallet. No descarga ninguna app.",
      },
      {
        title: "3. Canjean y vuelven",
        body: "Muestra su cupón en caja y tu personal lo valida al instante desde tu panel. Ya tiene un motivo para regresar.",
      },
    ],
    arcade: {
      label: "Terminal para negocios",
      title: "Convierte cada visita en una partida.",
      body:
        "Instala Kairos Arcade en tu negocio. Tus clientes juegan, alcanzan una meta y reciben un código para girar la ruleta y reclamar su recompensa desde Kairos.",
      benefits: [
        "Juegos cortos para el punto de venta.",
        "Recompensas vinculadas a cada sucursal.",
        "Marca y colores de tu negocio en pantalla.",
      ],
      previewLabel: "Vista previa de Kairos Arcade",
      previewTitle: "Elige un juego",
      previewStatus: "Terminal lista",
      games: ["Defensa Estelar", "Memory Rush", "Lane Racer", "Stack Tower", "Ruta Nebular", "Serpiente Golosa"],
      windows: "Descargar para Windows",
      linux: "Descargar para Linux",
      tablet: "Abrir en tableta",
      windowsPending: "Windows próximamente",
      linuxPending: "Linux próximamente",
      downloadNote: "En tableta, abre el enlace desde Chrome o Safari y agrégalo a la pantalla de inicio. Después vincúlala con tu cuenta y sucursal.",
      videoLabel: "Reproducir demo de Kairos Arcade",
      videoUnavailable: "La demo en video estará disponible pronto.",
    },
    stepsTitle: "Para empezar",
    steps: [
      "Crea tu negocio desde este panel.",
      "Define tu marca y colores para personalizar la Wallet.",
      "Crea tus sucursales y vincula tus máquinas Arcade con tu cuenta.",
      "Alta a tu personal de caja para validar cupones.",
    ],
    subs: {
      title: "Suscripciones y",
      titleWord: "planes",
      intro: "Empieza gratis. Cuando termine tu prueba, elige el plan que necesites.",
      plans: [
        { name: "Prueba", key: "TRIAL", body: "Ideal para dar tus primeros pasos." },
        { name: "Básico", key: "BASIC", body: "Perfecto para locales pequeños o medianos." },
        { name: "Pro", key: "PRO", body: "Pensado para crecer con varias sucursales." },
      ],
      logic:
        "Si tu suscripción se suspende, el negocio se bloquea de inmediato: nadie accede al panel, el personal de caja no puede validar cupones y las máquinas dejan de entregar recompensas. Tus datos se conservan y puedes reactivarlo cuando quieras.",
      note: "Pago desde el panel: próximamente.",
      startHere: "Empieza aquí",
      level: (n: number) => `Nivel ${n} de 3`,
      includedTitle: "Todos los planes incluyen",
      included: [
        "Máquina Arcade con tu marca",
        "Ruleta de recompensas",
        "Caja para validar cupones",
        "Panel de administración",
      ],
    },
    cta: "Listo para empezar",
    action: "Quiero empezar",
    trialAction: "Probar gratis",
  },
  tenants: {
    summary: "Resumen de negocios",
    title: "Panel de",
    titleWord: "negocios",
    new: "Nuevo negocio",
    search: "Buscar por nombre o identificador",
    allStatus: "Todos los estados",
    stats: { total: "Total", active: "Activos", suspended: "Suspendidos" },
    cols: { name: "Negocio", plan: "Plan", status: "Estado", ends: "Vence", actions: "Acciones" },
    empty: "Aún no hay negocios. Crea el primero para empezar.",
    emptyFiltered: "Ningún negocio coincide con la búsqueda.",
    noEnd: "Sin fecha",
    status: { ACTIVE: "Activo", SUSPENDED: "Suspendido", CANCELLED: "Cancelado" },
    plan: { TRIAL: "Prueba", BASIC: "Básico", PRO: "Pro" },
    requested: (plan: string) => `Pidió ${plan}`,
    suspend: "Suspender",
    activate: "Reactivar",
    suspendTitle: "¿Suspender este negocio?",
    suspendBody: (n: string) =>
      `${n} y su personal perderán el acceso de inmediato y se cerrarán sus sesiones. Sus datos se conservan y puedes reactivarlo cuando quieras.`,
    activateTitle: "¿Reactivar este negocio?",
    activateBody: (n: string) => `${n} podrá volver a iniciar sesión.`,
    suspended: (n: string) => `${n} fue suspendido`,
    activated: (n: string) => `${n} fue reactivado`,
    prev: "Anterior",
    next: "Siguiente",
    page: (p: number, total: number) => `Página ${p} de ${total}`,
  },
  form: {
    titleNew: "Nuevo",
    titleNewWord: "negocio",
    titleEdit: "Editar",
    sections: {
      business: "Datos del negocio",
      subscription: "Suscripción",
      brand: "Marca",
      points: "Economía de puntos",
      admin: "Administrador del negocio",
    },
    name: "Nombre comercial",
    slug: "Identificador (URL)",
    slugHint: "Minúsculas, números y guiones. No se puede cambiar después.",
    plan: "Plan",
    ends: "Vence el",
    primary: "Color principal",
    secondary: "Color secundario (opcional)",
    themeMode: "Tema de la Wallet",
    themeModes: { AUTO: "Automático", LIGHT: "Claro", DARK: "Oscuro" },
    scorePerPoint: "Puntos de juego por 1 punto",
    maxPointsPerGame: "Máximo de puntos por partida",
    maxGamesPerDay: "Máximo de partidas por día",
    createAdmin: "Crear el administrador ahora",
    adminHint: "Podrá iniciar sesión en el panel del negocio.",
    adminName: "Nombre",
    adminEmail: "Correo",
    adminPassword: "Contraseña (mínimo 10 caracteres)",
    created: (n: string) => `${n} fue creado`,
    saved: "Cambios guardados",
  },
  preview: {
    title: "Vista previa de la Wallet",
    balance: "Tu saldo",
    pts: "pts",
    redeem: "Canjear",
    reward: "Café gratis",
    cost: "500 pts",
    missing: "Te faltan 120 pts",
    missingN: (n: number) => `Te faltan ${n} pts`,
    canRedeem: "Ya puedes canjearlo",
    noRewards: "No hay premios visibles para tus clientes.",
    sampleNote: "Saldo de ejemplo. Solo se listan los premios visibles, de menor a mayor costo.",
    contrastText: "Contraste del texto",
    contrastBg: "Contraste sobre el fondo",
    light: "Claro",
    dark: "Oscuro",
    adjusted: "Ajustado automáticamente",
  },
  errors: {
    generic: "Algo salió mal. Intenta de nuevo.",
    network: "No se pudo conectar con el servidor.",
    required: "Campo obligatorio",
  },
  brand: {
    title: "Marca de tu",
    titleWord: "negocio",
    intro: "Así se verá tu negocio en la Wallet y en la máquina Arcade.",
    logo: "Logo",
    logoHint: "PNG, JPG o WebP. Máximo 1 MB. Mejor con fondo transparente.",
    upload: "Subir logo",
    replace: "Cambiar logo",
    remove: "Quitar logo",
    saved: "Marca actualizada",
  },
  upload: {
    badType: "Usa una imagen PNG, JPG o WebP",
    tooBig: "La imagen supera 1 MB",
    failed: "No se pudo subir la imagen",
    uploading: "Subiendo…",
  },
  rewards: {
    title: "Catálogo de",
    titleWord: "premios",
    intro: "Lo que tus clientes pueden canjear con sus puntos.",
    new: "Nuevo premio",
    empty: "Aún no tienes premios. Crea el primero para que tus clientes tengan algo que ganar.",
    cost: "Costo en puntos",
    stock: "Existencias",
    stockHint: "Déjalo vacío si no tiene límite.",
    unlimited: "Sin límite",
    left: (n: number) => `${n} disponibles`,
    soldOut: "Agotado",
    inactive: "Oculto",
    visible: "Visible",
    viewAsCustomer: "Ver como cliente",
    filterLabel: "Filtrar premios",
    filterAll: "Todos",
    filterVisible: "Visibles",
    filterHidden: "Ocultos",
    counts: (v: number, h: number) => `${v} ${v === 1 ? "visible" : "visibles"} · ${h} ${h === 1 ? "oculto" : "ocultos"}`,
    emptyFilter: "No hay premios en este filtro.",
    previewTitle: "Así lo verá el cliente",
    statusLive: "Los clientes lo ven",
    statusSoldOut: "Visible, agotado",
    statusHidden: "Oculto para clientes",
    visibilitySwitch: "Visible para clientes",
    show: (name: string) => `Mostrar ${name} para clientes`,
    hide: (name: string) => `Ocultar ${name} para clientes`,
    shown: "Premio visible para clientes",
    hidden: "Premio oculto para clientes",
    visibilityError: "No se pudo cambiar la visibilidad. Intenta de nuevo.",
    invalidCost: "Debe ser un entero mayor a 0",
    invalidStock: "Debe ser un entero de 0 o más",
    active: "Visible para clientes",
    name: "Nombre del premio",
    description: "Descripción (opcional)",
    image: "Imagen (opcional)",
    editTitle: "Editar premio",
    newTitle: "Nuevo premio",
    deleteTitle: "¿Eliminar este premio?",
    deleteBody: (n: string) => `${n} dejará de aparecer para tus clientes. Los cupones que ya se emitieron siguen siendo válidos.`,
    delete: "Eliminar",
    saved: "Premio guardado",
    deleted: "Premio eliminado",
    pts: "pts",
    readOnly: "Solo el administrador puede editar el catálogo.",
  },
  caja: {
    title: "Validar",
    titleWord: "cupón",
    intro: "Pide al cliente el código que muestra su teléfono.",
    code: "Código del cupón",
    lookup: "Buscar",
    redeem: "Marcar como entregado",
    another: "Validar otro cupón",
    notFound: "No encontramos ese código. Revisa que esté bien escrito.",
    delivered: "Entregado. Cupón canjeado",
    expiresIn: (m: number) => (m <= 1 ? "Vence en menos de 1 minuto" : `Vence en ${m} min`),
    status: { PENDING: "Listo para entregar", REDEEMED: "Ya canjeado", EXPIRED: "Vencido", CANCELLED: "Cancelado" },
    statusHelp: {
      PENDING: "Entrega el premio y confirma.",
      REDEEMED: "Este cupón ya se usó. No entregues el premio otra vez.",
      EXPIRED: "El cliente debe generar un cupón nuevo.",
      CANCELLED: "Este cupón fue cancelado. No entregues el premio.",
    },
    recent: "Entregas recientes",
    noRecent: "Todavía no hay entregas.",
    by: (n: string) => `por ${n}`,
  },
  stores: {
    title: "Sucursales y",
    titleWord: "máquinas",
    intro: "Vincula tabletas web con un código temporal o registra una terminal de escritorio con su llave pública.",
    new: "Nueva sucursal",
    newTitle: "Nueva sucursal",
    editTitle: "Editar sucursal",
    name: "Nombre",
    address: "Dirección (opcional)",
    active: "Sucursal activa",
    inactive: "Inactiva",
    empty: "Aún no tienes sucursales. Crea la primera para registrar una máquina.",
    storeId: "ID de la sucursal",
    machineId: "ID de la máquina",
    copy: "Copiar",
    copied: "Copiado",
    machines: "Máquinas",
    noMachines: "Sin máquinas registradas.",
    addMachine: "Registrar máquina",
    linkTablet: "Vincular tableta",
    tabletTitle: "Vincular tableta",
    pairingCode: "Código mostrado en la tableta",
    tabletLabel: "Nombre de la tableta",
    tabletHint: "Abre Kairos Arcade en la tableta, inicia la vinculación y escribe aquí el código de 8 caracteres.",
    tabletSaved: "Tableta vinculada",
    webTerminal: "Terminal web",
    machineTitle: "Registrar máquina",
    machineLabel: "Nombre de la máquina",
    algorithm: "Algoritmo",
    publicKey: "Llave pública (PEM)",
    publicKeyHint: "Genera el par en tu equipo con: pnpm --filter @kairos/api gen:machine-key nombre. Pega aquí solo la pública. La privada nunca sale de la máquina.",
    machineActive: "Activa",
    machineRevoked: "Revocada",
    revoke: "Revocar",
    revokeTitle: "¿Revocar esta máquina?",
    revokeBody: (n: string) => `${n} dejará de acreditar puntos. Esto no se puede deshacer: para volver a usarla se registra una llave nueva.`,
    saved: "Sucursal guardada",
    machineSaved: "Máquina registrada",
    revoked: "Máquina revocada",
  },
  staff: {
    title: "Personal de",
    titleWord: "caja",
    intro: "Las personas que validan cupones en el mostrador.",
    new: "Nuevo empleado",
    newTitle: "Nuevo empleado",
    editTitle: "Editar empleado",
    name: "Nombre",
    email: "Correo",
    password: "Contraseña (mínimo 10 caracteres)",
    newPassword: "Nueva contraseña (opcional)",
    passwordHint: "Si la cambias, se cierran sus sesiones abiertas.",
    store: "Sucursal",
    allStores: "Todas las sucursales",
    cols: { name: "Empleado", store: "Sucursal", status: "Estado" },
    active: "Activo",
    inactive: "Desactivado",
    activate: "Activar",
    deactivate: "Desactivar",
    deactivateTitle: "¿Desactivar a este empleado?",
    deactivateBody: (n: string) => `${n} perderá el acceso de inmediato y se cerrarán sus sesiones.`,
    empty: "Aún no tienes personal de caja.",
    saved: "Empleado guardado",
    deactivated: "Empleado desactivado",
    activated: "Empleado activado",
    admin: "Administrador",
  },
};
